workdir = "/tmp/iden3-CIT"
listen = "127.0.0.1:8010"

repos = [
    "https://github.com/iden3/go-iden3.git",
    "https://github.com/iden3/notifications-server.git",
    # "https://github.com/iden3/tx-forwarder.git",
    "https://github.com/iden3/iden3js.git",
]

[timeouts]
loop = 600
ready = 30
test = 120
setup = 120
stop = 120
hook = 60

[script.go-iden3.start_nameserver]
readystr = "Service API is ready at"

[script.go-iden3.start_relay]
readystr = "Service API is ready at"

[script.go-iden3.start_backupserver]
readystr = "Service API is ready at"

[script.go-iden3.start_claimserver]
readystr = "Service API is ready at"

[script.notifications-server.start_notificationserver]
readystr = "Service API is ready at"

[script.tx-forwarder.start_txforwarder]
readystr = "Service API is ready at"

[repo.go-iden3]
branch = "master"
# branch = "feature/serverready"

[repo.iden3js]
branch = "master"
# branch = "feature/asynctests"

[docker]
# image = "docker.io/library/alpine:3.9"
image = "docker.io/library/debian:jessie"
pull = false

[docker.binds]
"/home/dev/git/iden3/private-configs/" = "/home/dev/git/iden3/private-configs/"
# "/etc/ssl/certs/" = "/etc/ssl/certs/"
# "/etc/ca-certificates/" = "/etc/ca-certificates/"
